<?php
define("USUARIO", "ACEA");
define("PASSWORD", "HTC_3K3");
define("STRING_CONEXION", "(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.1.146)(PORT = 1521)))(CONNECT_DATA=(SID=ACEA)))");
