<?php
define("USUARIO", "ACEASOFT");
define("PASSWORD", "acea");
define("STRING_CONEXION", "(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.1.181)(PORT = 1521)))(CONNECT_DATA=(SID=ORCL)))");
