<?php
define("USUARIO", "ACEASOFT");
define("PASSWORD", "acea");
define("STRING_CONEXION", "(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.1.181)(PORT = 1521)))(CONNECT_DATA=(SID=ORCL)))");
//define("STRING_CONEXION", "(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.1.243)(PORT = 1521)))(CONNECT_DATA=(SID=ACEATEST)))");

define("USUARIO2", "ACEA");
define("PASSWORD2", "HTC_3K3");
define("STRING_CONEXION2", "(DESCRIPTION=(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.1.146)(PORT = 1521)))(CONNECT_DATA=(SID=ACEA)))");
