<?php
include_once 'class.conexion.php';
class ReportesRelPag extends ConexionClass{

	public function __construct()
	{
		parent::__construct();
	}

	//CONSULTAS RELACION DE PAGOS

    public function relacionPagos($proyecto, $fecini, $fecfin){
	    $partes = explode("-",$fecini);
	    $agno = $partes[0];
        $mes = $partes[1];
        $periodo = $agno.''.$mes;

        $sql = "SELECT P.ID_PAGO COD_PAGO, P.INM_CODIGO INMUEBLE, MP.VALOR IMPORTE_PAGADO,
       (SELECT SUM(PF.IMPORTE) FROM SGC_TT_PAGO_FACTURAS PF WHERE PF.ID_PAGO = P.ID_PAGO) IMPORTE_APLICADO,
       (SELECT COUNT(PF.ID_PAGO) FROM SGC_TT_PAGO_FACTURAS PF WHERE PF.ID_PAGO = P.ID_PAGO) NUM_FACTURAS,
       TO_CHAR(P.FECHA_PAGO,'DD/MM/YYYY')FECHA_PAGO,
      SUM((SELECT SUM(F.TOTAL_CREDITO) FROM SGC_TT_FACTURA F, SGC_TT_PAGO_FACTURAS PF
       WHERE F.INMUEBLE = I.CODIGO_INM AND PF.FACTURA = F.CONSEC_FACTURA AND PF.ID_PAGO = P.ID_PAGO))NOTA_CREDITO,
       SUM((SELECT SUM(F.TOTAL) FROM SGC_TT_FACTURA F, SGC_TT_PAGO_FACTURAS PF
       WHERE F.INMUEBLE = I.CODIGO_INM AND PF.FACTURA = F.CONSEC_FACTURA AND PF.ID_PAGO = P.ID_PAGO)) TOTAL_FACTURADO,
       (MP.VALOR - (SELECT SUM(PF.IMPORTE) FROM SGC_TT_PAGO_FACTURAS PF WHERE PF.ID_PAGO = P.ID_PAGO)) DIFERENCIA,
  E.COD_ENTIDAD, NVL(PP.COD_VIEJO,PP.ID_PUNTO_PAGO) PUNTO, C.NUM_CAJA, 'Recaudo' TIPO,
  DECODE(SI.COD_SERVICIO,'1','Agua','3','Pozo')SUMINISTRO, I.UNIDADES_HAB UNIDADES, P.REFERENCIA DESCRIPCION,
  DECODE(I.FACTURAR,'D','SI','P','NO')MEDIDOR, T.CATEGORIA, T.COD_USO USO,
  MAX((SELECT MAX(F.PERIODO) FROM SGC_TT_FACTURA F, SGC_TT_PAGO_FACTURAS PF
  WHERE F.INMUEBLE = I.CODIGO_INM AND PF.FACTURA = F.CONSEC_FACTURA AND PF.ID_PAGO = P.ID_PAGO)) PERMAX,
  MIN((SELECT MIN(F.PERIODO) FROM SGC_TT_FACTURA F, SGC_TT_PAGO_FACTURAS PF
  WHERE F.INMUEBLE = I.CODIGO_INM AND PF.FACTURA = F.CONSEC_FACTURA AND PF.ID_PAGO = P.ID_PAGO)) PERMIN,
  SUM((SELECT SUM(DF.VALOR * -1) FROM SGC_TT_FACTURA F, SGC_TT_PAGO_FACTURAS PF, SGC_TT_DETALLE_FACTURA DF
  WHERE F.INMUEBLE = I.CODIGO_INM AND PF.FACTURA = F.CONSEC_FACTURA AND PF.ID_PAGO = P.ID_PAGO
        AND DF.FACTURA = F.CONSEC_FACTURA AND DF.CONCEPTO IN (401,402,403,404,411,421,427))) SALDOANT,
  SI.COD_SERVICIO CONCEPTO, SI.CUPO_BASICO, I.ID_SECTOR, I.ID_RUTA, I.ID_ZONA, FP.DESCRIPCION DESCRIPCIONM
FROM SGC_TT_INMUEBLES I, SGC_TT_PAGOS P, SGC_TP_CAJAS_PAGO C, SGC_TP_PUNTO_PAGO PP, SGC_TP_ENTIDAD_PAGO E,
  SGC_TT_SERVICIOS_INMUEBLES SI,  SGC_TP_TARIFAS T, SGC_TT_SALDO_FAVOR SF, SGC_TT_MEDIOS_PAGO MP, SGC_TP_FORMA_PAGO FP
WHERE I.CODIGO_INM = P.INM_CODIGO
      AND I.CODIGO_INM = SI.COD_INMUEBLE(+)
      AND P.ID_CAJA = C.ID_CAJA
      AND MP.ID_PAGO=P.ID_PAGO
      AND PP.ID_PUNTO_PAGO = C.ID_PUNTO_PAGO
      AND FP.CODIGO=MP.ID_FORM_PAGO
      AND E.COD_ENTIDAD = PP.ENTIDAD_COD
      AND T.CONSEC_TARIFA(+) = SI.CONSEC_TARIFA
      AND SI.COD_SERVICIO (+) IN (1,3)
      AND SF.CODIGO_PAG(+) = P.ID_PAGO
      AND P.FECHA_PAGO BETWEEN TO_DATE('$fecini 00:00:00','YYYY-MM-DD HH24:MI:SS')
      AND TO_DATE('$fecfin 23:59:59','YYYY-MM-DD HH24:MI:SS')
      AND E.VALIDA_REPORTES='S'
      AND P.ESTADO='A'
      AND P.ACUEDUCTO = '$proyecto'
GROUP BY P.ID_PAGO, P.INM_CODIGO,TO_CHAR(P.FECHA_PAGO,'DD/MM/YYYY'), MP.VALOR, E.COD_ENTIDAD, PP.ID_PUNTO_PAGO, PP.COD_VIEJO,
  C.NUM_CAJA, I.UNIDADES_HAB, P.REFERENCIA, I.FACTURAR, T.CATEGORIA, T.COD_USO, SI.COD_SERVICIO, SI.CUPO_BASICO, I.ID_SECTOR, I.ID_RUTA, I.ID_ZONA, FP.DESCRIPCION
UNION
SELECT  R.CODIGO COD_PAGO, R.INMUEBLE INMUEBLE, MR.VALOR IMPORTE_PAGADO, R.APLICADO IMPORTE_APLICADO,
        SUM('0') NUM_FACTURAS, TO_CHAR(R.FECHA_PAGO,'DD/MM/YYYY')FECHA_PAGO, SUM(0) NOTA_CREDITO, SUM('0') TOTAL_FACTURADO,
        (MR.VALOR - R.APLICADO) DIFERENCIA, E.COD_ENTIDAD, NVL(PP.COD_VIEJO,PP.ID_PUNTO_PAGO) PUNTO, C.NUM_CAJA, 'Otro Recaudo' TIPO,
        DECODE(SI.COD_SERVICIO,'1','Agua','3','Pozo')SUMINISTRO, I.UNIDADES_HAB UNIDADES, R.DESCRIPCION DESCRIPCION,
        DECODE(I.FACTURAR,'D','SI','P','NO')MEDIDOR, T.CATEGORIA, T.COD_USO USO, MAX(0)PERMAX, MIN(0)PERMIN, SUM('0') SALDOANT, R.CONCEPTO,
  SI.CUPO_BASICO, I.ID_SECTOR, I.ID_RUTA, I.ID_ZONA, FP.DESCRIPCION DESCRIPCIONM
FROM SGC_TT_INMUEBLES I, SGC_TT_OTROS_RECAUDOS R, SGC_TP_CAJAS_PAGO C, SGC_TP_PUNTO_PAGO PP, SGC_TP_ENTIDAD_PAGO E, SGC_TT_FACTURA F,
  SGC_TT_APLICA_OTROSREC A, SGC_TT_SERVICIOS_INMUEBLES SI, SGC_TP_TARIFAS T, ACEASOFT.SGC_TT_MEDIOS_RECAUDO MR, SGC_TP_FORMA_PAGO FP
WHERE I.CODIGO_INM = R.INMUEBLE
      AND I.CODIGO_INM = SI.COD_INMUEBLE(+)
      AND R.CAJA = C.ID_CAJA
      AND MR.ID_OTRREC=R.CODIGO
      AND PP.ID_PUNTO_PAGO = C.ID_PUNTO_PAGO
      AND E.COD_ENTIDAD = PP.ENTIDAD_COD
      AND T.CONSEC_TARIFA(+) = SI.CONSEC_TARIFA
      AND F.INMUEBLE(+) = R.INMUEBLE
      AND A.ID_OTROREC(+) = R.CODIGO
      AND FP.CODIGO=MR.ID_FORM_PAGO
      AND R.FECHA_PAGO BETWEEN TO_DATE('$fecini 00:00:00','YYYY-MM-DD HH24:MI:SS')
      AND TO_DATE('$fecfin 23:59:59','YYYY-MM-DD HH24:MI:SS')
      AND R.ESTADO IN ('T','A')
      AND E.ACTIVO IN ('S')
      AND R.CAJA NOT IN (463,391)
      AND R.ACUEDUCTO = '$proyecto'
      AND SI.COD_SERVICIO (+) IN (1,3)
GROUP BY
  R.CODIGO, R.INMUEBLE, TO_CHAR(R.FECHA_PAGO,'DD/MM/YYYY'), MR.VALOR, R.APLICADO, E.COD_ENTIDAD, PP.ID_PUNTO_PAGO, PP.COD_VIEJO,
  C.NUM_CAJA, SI.COD_SERVICIO, I.UNIDADES_HAB, R.DESCRIPCION, I.FACTURAR, T.CATEGORIA, R.CONCEPTO, SI.CUPO_BASICO, T.COD_USO, I.ID_SECTOR, I.ID_RUTA, I.ID_ZONA, FP.DESCRIPCION
ORDER BY 2";
		//echo $sql;
		$resultado = oci_parse($this->_db,$sql);
		$banderas=oci_execute($resultado);
		if($banderas==TRUE)
		{
			oci_close($this->_db);
			return $resultado;
		}
		else
		{
			oci_close($this->_db);
			echo "false";
			return false;
		}
	
	}
}